export const SELECT_CHANNEL = "SELECT_CHANNEL";
export const SELECT_USER = "SELECT_USER";
export const SET_MESSAGES = 'SET_MESSAGES';

export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
export const SEND_MESSAGE_INIT = 'SEND_MESSAGE_INIT';

export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';
export const FETCH_MESSAGES_INIT = 'FETCH_MESSAGES_INIT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const CONFIRM_FIRST_AUTH = 'CONFIRM_FIRST_AUTH';
export const ENABLE_AUTH_LISTENER = 'ENABLE_AUTH_LISTENER';
export const UPDATE_AUTH_OBJECT_START = 'UPDATE_AUTH_OBJECT_START';
export const UPDATE_AUTH_OBJECT_SUCCESS = 'UPDATE_AUTH_OBJECT_SUCCESS';
export const UPDATE_AUTH_OBJECT_FAIL = 'UPDATE_AUTH_OBJECT_FAIL';

export const SET_AUTH_OBJECT = 'SET_AUTH_OBJECT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const SELECT_FILE = 'SELECT_FILE';